This is to be merged at the same time or after 2.4.6 is released, which fixes the following bugs related to the OpenLP importer:
- Added all of the Finnish songs to a songbook
- Removed one duplicated song
- A couple of typos fixed in the song titles

Bug #1652003: OpenLP Importer 2 fails to import song numbers 2.4 >
Bug #1632567: OpenLP importer can't handle new song songbook DB structure (AttributeError: 'OldSong' object has no attribute 'book')
(Bug #652004:  OpenLP Importer 2 does not support author types)